-- ============================================================================
-- Email alerts for job creation — database side.
-- Run this whole file in the Supabase SQL editor. Safe to re-run.
--
-- See docs/JOB-ALERTS.md for the full setup (Resend account, function secrets,
-- deploy commands). This file only does the database half.
--
-- SAFETY NOTE, given the 29 Jul 2026 outage: the trigger below uses pg_net,
-- which QUEUES the HTTP request and returns immediately. It cannot block a job
-- insert, and it cannot fail one — if the edge function is down, unreachable or
-- misconfigured, the job still saves. Never replace this with a synchronous
-- call. See docs/DATABASE-CHANGES.md.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Alert log.
--    Three jobs: an audit trail of what was alerted, the counter the rate cap
--    reads, and the source a daily digest would read if you ever switch from
--    per-job emails to a summary.
-- ---------------------------------------------------------------------------
create table if not exists public.job_alerts (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('created', 'failed')),
  job_label text,
  detail text,
  emailed boolean not null default false,
  suppressed boolean not null default false,   -- true when the rate cap skipped the email
  created_at timestamptz not null default now()
);

create index if not exists job_alerts_created_at_idx on public.job_alerts (created_at desc);

alter table public.job_alerts enable row level security;

-- Only admins can read the log; nothing writes to it except the edge function
-- (service role bypasses RLS). No INSERT/UPDATE/DELETE policy is defined on
-- purpose — the client has no business writing here.
drop policy if exists "job_alerts select admin" on public.job_alerts;
create policy "job_alerts select admin" on public.job_alerts
  for select to authenticated using (private.is_admin());

-- ---------------------------------------------------------------------------
-- 2. Fire the edge function whenever a job row is inserted.
--    This is the "success" half. It is server-side on purpose: a client-side
--    hook would miss any insert made outside the app (SQL editor, a script,
--    another device) and could be skipped by a browser that dies mid-request.
--
--    pg_net is the same mechanism the Dashboard's Database Webhooks UI
--    generates; doing it here keeps it in version control.
-- ---------------------------------------------------------------------------
create extension if not exists pg_net with schema extensions;

-- Store the function URL and key in Vault rather than inlining a service key
-- in the trigger body. Set these once (replace the values):
--
--   select vault.create_secret('https://<project-ref>.supabase.co/functions/v1/notify-job-event', 'job_alert_url');
--   select vault.create_secret('<your anon key>', 'job_alert_key');
--
-- Re-running create_secret with an existing name errors; use vault.update_secret
-- to change one. Read them back with:
--   select name from vault.decrypted_secrets;

create or replace function public.notify_job_created()
returns trigger
language plpgsql
security definer set search_path = public, extensions
as $$
declare
  fn_url text;
  fn_key text;
begin
  -- Any failure in here must NOT take the insert down with it, so the whole
  -- body is wrapped and errors are swallowed. A missed alert is an
  -- inconvenience; a job that won't save is an outage.
  begin
    select decrypted_secret into fn_url from vault.decrypted_secrets where name = 'job_alert_url';
    select decrypted_secret into fn_key from vault.decrypted_secrets where name = 'job_alert_key';
    if fn_url is null or fn_key is null then
      return new;
    end if;

    perform net.http_post(
      url := fn_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || fn_key
      ),
      body := jsonb_build_object(
        'source', 'db_trigger',
        'kind', 'created',
        'job', jsonb_build_object(
          'id', new.id,
          'asm', new.asm,
          'so', new.so,
          'cust', new.cust,
          'type', new.type,
          'alloc', new.alloc,
          'due_date', new.due_date,
          'status', new.status
        )
      )
    );
  exception when others then
    -- Deliberately silent. Do not re-raise.
    null;
  end;
  return new;
end;
$$;

revoke all on function public.notify_job_created() from public, anon, authenticated;

drop trigger if exists on_job_created on public.jobs;
create trigger on_job_created
  after insert on public.jobs
  for each row execute function public.notify_job_created();

-- ---------------------------------------------------------------------------
-- 3. Handy checks
-- ---------------------------------------------------------------------------
-- Recent alerts:
--   select created_at, kind, job_label, emailed, suppressed, detail
--   from public.job_alerts order by created_at desc limit 20;
--
-- Turn the success emails off without removing anything:
--   alter table public.jobs disable trigger on_job_created;
-- ...and back on:
--   alter table public.jobs enable trigger on_job_created;
