-- ============================================================================
-- Flexachem Workshop Tracker — Supabase setup for auth, audit & PDF attachments
-- Run this whole file in the Supabase SQL editor (Dashboard → SQL → New query).
-- Safe to re-run: statements are idempotent where possible.
--
-- Also required in the Dashboard (not SQL):
--   1. Authentication → Providers → Email: ENABLE.
--      For an internal tool, consider disabling "Confirm email" so people can
--      sign in immediately. If you keep confirmation on, set Authentication →
--      URL Configuration → Site URL to your deployed app URL.
--   2. After YOUR first signup in the app, run the "bootstrap first admin"
--      statement at the bottom of this file.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Profiles: one row per login account, carrying the app role.
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  name text,
  role text not null default 'staff' check (role in ('admin', 'staff')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Auto-create a profile when someone signs up (name comes from the signup form).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Helper used by RLS policies. SECURITY DEFINER so it can read profiles
-- without recursing through profiles' own RLS.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and active
  );
$$;

-- ---------------------------------------------------------------------------
-- 2. Jobs table: new columns for PDF attachments and soft delete.
--    (The jobs table is created by the app's normal use; we only add columns.)
-- ---------------------------------------------------------------------------
alter table public.jobs add column if not exists attachment jsonb;
alter table public.jobs add column if not exists deleted boolean not null default false;
-- Completion time + manual close-out flag. The board's Complete column shows only jobs
-- completed in the current week (since the last Saturday midnight); older completed jobs
-- and manually-archived ones drop off the board but stay in the Master List forever.
-- Jobs completed before completed_at existed keep null here and the app falls back to
-- updated_at, so no backfill is required.
alter table public.jobs add column if not exists completed_at timestamptz;
alter table public.jobs add column if not exists archived boolean not null default false;

-- ---------------------------------------------------------------------------
-- 2a. Auto-generate jobs.id on insert.
--     The app inserts jobs without supplying an id and reads back whatever id
--     the database assigns. If jobs.id has no identity/default, every insert
--     fails with 23502 (null id) and later edits fail with 22P02. We keep the
--     column as bigint (so the notes.job_id foreign key stays valid) and just
--     attach an identity sequence, advanced past any existing rows.
--     Idempotent: skips if the column is already an identity column.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.jobs'::regclass
      and attname = 'id'
      and attidentity in ('a', 'd')  -- ALWAYS / BY DEFAULT
  ) then
    execute 'alter table public.jobs alter column id drop default';
    execute 'alter table public.jobs alter column id add generated by default as identity';
    perform setval(
      pg_get_serial_sequence('public.jobs', 'id'),
      coalesce((select max(id) from public.jobs), 0) + 1,
      false
    );
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2b. Staff & job-type catalogues.
--     These may only have existed in browser storage until now. Created here
--     (if missing) with the exact columns the app writes, so cloud sync works
--     and the RLS section below has real tables to secure. Ids are text
--     (e.g. 'staff-darragh', 'jobtype-valve-assembly') — not uuids.
-- ---------------------------------------------------------------------------
create table if not exists public.staff (
  id text primary key,
  name text not null,
  role text,
  active boolean not null default true,
  email text,
  phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.job_types (
  id text primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2c. Customers catalogue (mirrors job_types). Ids are text slugs
--     (e.g. 'customer-ge-whitegate'). Seeded with this week's schedule.
-- ---------------------------------------------------------------------------
create table if not exists public.customers (
  id text primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.customers (id, name) values
  ('customer-ge-whitegate', 'GE Whitegate'),
  ('customer-itw-performance-polymers', 'ITW Performance Polymers'),
  ('customer-bms', 'BMS'),
  ('customer-shannon-bridge', 'Shannon Bridge'),
  ('customer-ha-o-neil', 'HA O Neil'),
  ('customer-eli-lilly', 'Eli Lilly'),
  ('customer-pm-group', 'PM Group'),
  ('customer-radleys', 'Radleys'),
  ('customer-regeneron', 'Regeneron'),
  ('customer-msd-ballydine', 'MSD Ballydine'),
  ('customer-paciv-eli-lilly', 'Paciv / Eli Lilly')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 3. Storage bucket for job PDFs (private; the app uses signed URLs).
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('job-files', 'job-files', false)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 4. Row Level Security.
--    THE HARD BOUNDARY: signed-in users can read everything and update jobs
--    (staff move statuses / post notes); only admins can create or delete
--    jobs and manage staff, job types and accounts.
--    NOTE: "staff may only change status/notes" is enforced by the app UI,
--    not by RLS — column-level rules aren't practical here. Acceptable for an
--    internal tool; the table-level rules below are the real security line.
-- ---------------------------------------------------------------------------
alter table public.jobs enable row level security;
alter table public.staff enable row level security;
alter table public.job_types enable row level security;
alter table public.customers enable row level security;
alter table public.profiles enable row level security;

-- jobs
drop policy if exists "jobs select authenticated" on public.jobs;
create policy "jobs select authenticated" on public.jobs for select to authenticated using (true);
drop policy if exists "jobs update authenticated" on public.jobs;
create policy "jobs update authenticated" on public.jobs for update to authenticated using (true) with check (true);
drop policy if exists "jobs insert admin" on public.jobs;
create policy "jobs insert admin" on public.jobs for insert to authenticated with check (public.is_admin());
drop policy if exists "jobs delete admin" on public.jobs;
create policy "jobs delete admin" on public.jobs for delete to authenticated using (public.is_admin());

-- staff
drop policy if exists "staff select authenticated" on public.staff;
create policy "staff select authenticated" on public.staff for select to authenticated using (true);
drop policy if exists "staff write admin" on public.staff;
create policy "staff write admin" on public.staff for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- job_types
drop policy if exists "job_types select authenticated" on public.job_types;
create policy "job_types select authenticated" on public.job_types for select to authenticated using (true);
drop policy if exists "job_types write admin" on public.job_types;
create policy "job_types write admin" on public.job_types for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- customers
drop policy if exists "customers select authenticated" on public.customers;
create policy "customers select authenticated" on public.customers for select to authenticated using (true);
drop policy if exists "customers write admin" on public.customers;
create policy "customers write admin" on public.customers for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- profiles
drop policy if exists "profiles select authenticated" on public.profiles;
create policy "profiles select authenticated" on public.profiles for select to authenticated using (true);
drop policy if exists "profiles update admin" on public.profiles;
create policy "profiles update admin" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- storage: job-files bucket (read for signed-in users, writes for admins)
drop policy if exists "job files read" on storage.objects;
create policy "job files read" on storage.objects for select to authenticated using (bucket_id = 'job-files');
drop policy if exists "job files insert admin" on storage.objects;
create policy "job files insert admin" on storage.objects for insert to authenticated with check (bucket_id = 'job-files' and public.is_admin());
drop policy if exists "job files update admin" on storage.objects;
create policy "job files update admin" on storage.objects for update to authenticated using (bucket_id = 'job-files' and public.is_admin());
drop policy if exists "job files delete admin" on storage.objects;
create policy "job files delete admin" on storage.objects for delete to authenticated using (bucket_id = 'job-files' and public.is_admin());

-- ---------------------------------------------------------------------------
-- 5. Bootstrap the first admin AFTER signing up in the app.
--    Replace the email if needed, then run:
-- ---------------------------------------------------------------------------
-- update public.profiles set role = 'admin' where email = 'padraigbrosnan@gmail.com';

-- ---------------------------------------------------------------------------
-- 6. Per-account theme preference.
--    profiles UPDATE stays admin-only (users must not change their own role).
--    Non-admins persist their theme through a SECURITY DEFINER RPC that can only
--    touch auth.uid()'s own theme column. Run this whole block in the SQL editor.
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column if not exists theme text not null default 'light'
  check (theme in ('light', 'dark', 'system'));

create or replace function public.set_my_theme(new_theme text)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if new_theme is null or new_theme not in ('light', 'dark', 'system') then
    raise exception 'invalid theme: %', new_theme;
  end if;
  update public.profiles
     set theme = new_theme, updated_at = now()
   where id = auth.uid();
end;
$$;

revoke all on function public.set_my_theme(text) from public;
grant execute on function public.set_my_theme(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 7. Realtime for the board (live sync across devices).
--    If the supabase_realtime publication already exists (it does by default),
--    this adds the jobs table to it. You can also toggle Realtime for `jobs`
--    from the dashboard: Database → Replication.
-- ---------------------------------------------------------------------------
alter publication supabase_realtime add table public.jobs;

-- ---------------------------------------------------------------------------
-- 8. Notifications (@-mentions in job notes).
--    Each row targets one login account. job_id is TEXT with no FK: jobs.id is
--    bigint in cloud but a string id in demo, and jobs use soft delete.
-- ---------------------------------------------------------------------------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  actor text not null default '',
  job_id text,
  job_label text,
  excerpt text not null default '',
  read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;

-- Users can only ever see / modify their OWN notifications.
drop policy if exists "notifications select own" on public.notifications;
create policy "notifications select own" on public.notifications for select to authenticated using (user_id = auth.uid());
drop policy if exists "notifications update own" on public.notifications;
create policy "notifications update own" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "notifications delete own" on public.notifications;
create policy "notifications delete own" on public.notifications for delete to authenticated using (user_id = auth.uid());

-- Cross-user inserts go through this SECURITY DEFINER RPC — there is deliberately
-- NO insert policy. The actor name is derived from auth.uid() (so it can't be
-- spoofed), self- and inactive-targets are skipped, and anon callers are rejected.
create or replace function public.notify_mentions(target_ids uuid[], p_job_id text, p_job_label text, p_excerpt text)
returns void
language plpgsql
security definer set search_path = public
as $$
declare actor_name text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  select coalesce(name, email, 'Workshop') into actor_name from public.profiles where id = auth.uid();
  insert into public.notifications (user_id, actor, job_id, job_label, excerpt)
  select distinct t, actor_name, p_job_id, p_job_label, left(coalesce(p_excerpt, ''), 200)
  from unnest(target_ids) as t
  where t <> auth.uid()
    and exists (select 1 from public.profiles p where p.id = t and p.active);
end;
$$;

revoke all on function public.notify_mentions(uuid[], text, text, text) from public;
grant execute on function public.notify_mentions(uuid[], text, text, text) to authenticated;

-- Add notifications to realtime so the bell updates live. Wrapped for idempotency.
do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- 9. Push tokens (Android FCM). Only used if you complete the Firebase setup in
--    BUILD_APK.md. Each device registers its token here; the notify-push Edge
--    Function reads them with the service-role key (which bypasses RLS) and sends
--    FCM messages. Users can only see/modify their OWN tokens.
-- ---------------------------------------------------------------------------
create table if not exists public.push_tokens (
  token text primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  platform text not null default 'android',
  updated_at timestamptz not null default now()
);
alter table public.push_tokens enable row level security;
drop policy if exists "push tokens own" on public.push_tokens;
create policy "push tokens own" on public.push_tokens for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
