-- ===========================================================================
-- Applied to production 30 Jul 2026 via the Supabase MCP connector as two
-- migrations: install_job_alerts_table, then schedule_sweep_job_errors_hourly.
-- Recorded here so the repo matches the live database.
--
-- Decision: alerting is FAILURE-ONLY. The notify_job_created function and the
-- on_job_created trigger in supabase/alerts-setup.sql are deliberately NOT
-- installed — no per-job confirmation email is wanted.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. The alert log.
--
--    Both notify-job-event and sweep-job-errors write here, and
--    notify-job-event's hourly rate cap COUNTS this table. It was missing
--    entirely, so those inserts failed silently and the cap always read zero —
--    a retry loop or bulk import would have mailed unboundedly, which is how an
--    alert channel gets muted and stops being read at all.
-- ---------------------------------------------------------------------------
create table if not exists public.job_alerts (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('created', 'failed')),
  job_label text,
  detail text,
  emailed boolean not null default false,
  suppressed boolean not null default false,   -- true when the rate cap skipped the email
  created_at timestamptz not null default now()
);

create index if not exists job_alerts_created_at_idx on public.job_alerts (created_at desc);

alter table public.job_alerts enable row level security;

-- Admins read; nothing writes except the edge functions via the service role, which bypasses
-- RLS. No INSERT/UPDATE/DELETE policy on purpose — the client has no business writing here.
drop policy if exists "job_alerts select admin" on public.job_alerts;
create policy "job_alerts select admin" on public.job_alerts
  for select to authenticated using (private.is_admin());

-- ---------------------------------------------------------------------------
-- 2. Schedule the log sweeper.
--
--    sweep-job-errors is the only net that catches a rejected write where the
--    browser died before it could report — the 29 Jul 2026 failure mode. It had
--    been deployed since 30 Jul and had NEVER run: pg_cron was not installed and
--    nothing scheduled it.
-- ---------------------------------------------------------------------------
create extension if not exists pg_cron;

-- Unschedule first so re-running this file is safe.
do $$
begin
  perform cron.unschedule('sweep-job-errors');
exception when others then null;
end $$;

-- Hourly, matching the function's default SWEEP_WINDOW_MINUTES of 60. The interval and the
-- window MUST agree — a shorter interval with a 60-minute window re-reports the same errors.
select cron.schedule(
  'sweep-job-errors',
  '7 * * * *',   -- off the hour boundary, where every other cron piles up
  $$
    select net.http_post(
      url := 'https://pxekejsjwxlrnaufmjxo.supabase.co/functions/v1/sweep-job-errors',
      headers := jsonb_build_object('Content-Type', 'application/json')
    );
  $$
);

-- ---------------------------------------------------------------------------
-- OUTSTANDING after this migration — the schedule alone is not enough.
--
--   Triggering the function manually returned:
--     500 {"error":"SUPABASE_MGMT_TOKEN / SUPABASE_PROJECT_REF not set"}
--
--   Until both are set under Edge Functions → Secrets, the cron fires hourly and
--   the sweeper does nothing. Nothing surfaces that failure on its own; the only
--   trace is net._http_response:
--
--     select id, status_code, left(content, 200) from net._http_response
--     order by id desc limit 5;
--
--   SUPABASE_PROJECT_REF = pxekejsjwxlrnaufmjxo
--   SUPABASE_MGMT_TOKEN  = a personal access token, created by a human at
--                          supabase.com/dashboard/account/tokens
--
--   Also unverified: RESEND_API_KEY / ALERT_EMAIL_TO (used by both alert
--   functions) and ALERT_WEBHOOK_SECRET.
--
-- NOTE ON EXPOSURE: sweep-job-errors is deployed with verify_jwt = false and
-- performs no auth check of its own, so anyone who knows the URL can trigger it.
-- It only reads logs and mails ALERT_EMAIL_TO, but that is an inbox-flood vector.
-- notify-job-event guards itself with an x-alert-secret header; the sweeper could
-- do the same.
-- ---------------------------------------------------------------------------
